= _**Java** aktuell_ Artikelvorlage im Asciidoc Format
:reproducible:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[IMPORTANT]
.Diese Vorlage ist noch im Beta-Stadium
====
Bevor du sie benutzt, spreche das bitte mit Marcus Fihlon ab. Vielen Dank! Möglichkeiten zur Kontaktaufnahme:

* E-Mail: mailto:marcus@fihlon.swiss[marcus@fihlon.swiss]
* Matrix: https://matrix.to/#/@mcpringle:matrix.org[@mcpringle:matrix.org]
* Mastodon: https://fosstodon.org/@McPringle[@McPringle@fosstodon.org ]
====

== Informationen für Autoren

* Die eigentliche Vorlage befindet sich in der Datei link:article.adoc[article.adoc]. Alle anderen Dateien kannst du ignorieren.
* Wenn du zusammen mit einem oder mehreren anderen Autoren am Artikel arbeitest, so kannst du diese in Zeile 2 mit Semikolon `;` getrennt aufführen. Bitte nicht auf mehrere Zeilen verteilen!
* Wenn du möchtest, kannst du für deine Bilder ein eigenes Verzeichnis anlegen. Passe dann das Attribut `:imagesdir:` entsprechend an. Verwende immer relative Verzeichnisangaben, niemals absolute.
* Vergiss nicht, beim Einreichen alle nötigen Dateien (Bilder, Quelltext, etc.) mitzuschicken. Sende dazu entweder eine ZIP-Datei per E-Mail an mailto:marcus@fihlon.swiss[Marcus Fihlon] (Verschlüsselung per https://keys.openpgp.org/search?q=marcus.fihlon%40jug.ch[GnuPG] möglich) oder verwende ein GitHub-Repository. Ist das GitHub-Repository privat, lade bitte link:https://github.com/McPringle[Marcus Fihlon] mit entsprechenden Berechtigungen in das GitHub-Repository ein.


== Informationen für die Redaktion

=== Ausgabe-Dateien generieren

Um aus einer Asciidoc-Datei die verschiedenen Ausgabe-Dateien (HTML, PDF, XML, Word) zu generieren, werden die Kommandozeilen-Tools https://asciidoctor.org/[Asciidoctor] mit der Erweiterung https://github.com/Alwinator/asciidoctor-lists[asciidoctor-lists] und https://pandoc.org/[Pandoc] benötigt. Die entsprechenden Aufrufe befinden sich im Shell-Skript link:compile.sh[compile.sh]. Das Skript konvertiert die Datei link:article.adoc[article.adoc] im aktuellen Verzeichnis. Um die automatisch erzeugten Dateien wieder zu löschen, kann das Skript link:clean.sh[clean.sh] aufgerufen werden.
