= _**Java** aktuell_ Artikelvorlage im Asiidoc Format
:reproducible:

Die Vorlage befindet sich in der Datei link:article.adoc[article.adoc].


== Wichtige Hinweise

- Wenn mehrere Autoren am Artikel arbeiten, so können diese in Zeile 2 mit Semikolon `;` getrennt aufgeführt werden. Bitte nicht auf mehrere Zeilen verteilen!

- Wenn Du möchtest, kannst Du für deine Bilder ein eigenes Verzeichnis anlegen. Passe dann das Attribut `:imagesdir:` entsprechend an. Verwende immer relative Verzeichnisangaben, niemals absolute.


== Ausgabe-Dateien generieren

Um aus einer Asciidoc-Datei die verschiedenen Ausgabe-Dateien (HTML, PDF, XML, Word) zu generieren, werden die Kommandozeilen-Tools https://asciidoctor.org/[Asciidoctor] mit der Erweiterung https://github.com/Alwinator/asciidoctor-lists[asciidoctor-lists] und https://pandoc.org/[Pandoc] benötigt. Die entsprechenden Aufrufe befindet sich im Shell-Skript link:compile.sh[compile.sh]. Das Skript konvertiert die Datei link:article.adoc[article.adoc] im aktuellen Verzeichnis.
